/**
 * Whisper read/write for the global mental model.
 * Storage: mind/whisper.txt
 *
 * Whispers are pre-generated, injection-ready paragraphs (~300 tokens).
 * Generated by the compressor, read at session start.
 */
import fs from "fs";
import path from "path";
import { CONFIG } from "../config.js";

const MAX_GLOBAL_WHISPER_TOKENS = 400;

export function whisperPath(): string {
  return path.join(CONFIG.paths.v3Mind, "whisper.txt");
}

export function readWhisper(): string | null {
  const filePath = whisperPath();
  if (!fs.existsSync(filePath)) return null;
  const content = fs.readFileSync(filePath, "utf-8").trim();
  return content || null;
}

export function writeWhisper(text: string): void {
  const dir = CONFIG.paths.v3Mind;
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(whisperPath(), text);
}

export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export function enforceWhisperCap(text: string): string {
  const tokens = estimateTokens(text);
  if (tokens <= MAX_GLOBAL_WHISPER_TOKENS) return text;
  const charBudget = MAX_GLOBAL_WHISPER_TOKENS * 4;
  const trimmed = text.slice(0, charBudget);
  const lastPeriod = trimmed.lastIndexOf(".");
  if (lastPeriod > charBudget * 0.7) {
    return trimmed.slice(0, lastPeriod + 1);
  }
  return trimmed;
}
