import fs from "fs";
import path from "path";
import { CONFIG } from "../config.js";
import { readModel as readGlobalModel } from "../mind/model.js";
import { readModel as readProjectModel } from "../lenses/manager.js";
import { readObservations as readGlobalObservations } from "../mind/observations.js";
import { readObservations as readProjectObservations } from "../lenses/manager.js";
import { getAntiPatterns, getByProject } from "./graph-index.js";
import { ADAPTER_CONFIGS, HarnessType } from "../adapters/types.js";
import { activityBus } from "../events.js";

const CUSTOM_START = "<!-- custom start -->";
const CUSTOM_END = "<!-- custom end -->";
const GRAPH_MEMORY_MARKER = "<!-- graph-memory:bootstrap -->";

export interface BootstrapResult {
  filePath: string;
  created: boolean;
  sections: string[];
}

export function resolveDocPath(cwd: string, harness: string): string {
  const adapterConfig = ADAPTER_CONFIGS[harness as HarnessType] || ADAPTER_CONFIGS["opencode"];
  let filename = adapterConfig.projectDocFilename;

  if (harness === "claude-code" && !fs.existsSync(path.join(cwd, "CLAUDE.md"))) {
    const claudeDir = path.join(cwd, ".claude");
    if (fs.existsSync(claudeDir)) {
      return path.join(claudeDir, filename);
    }
  }

  if (harness !== "claude-code" && fs.existsSync(path.join(cwd, "CLAUDE.md")) && !fs.existsSync(path.join(cwd, "AGENT.md"))) {
    filename = "CLAUDE.md";
  }

  return path.join(cwd, filename);
}

export function extractCustomSections(content: string): string {
  const sections: string[] = [];
  let start = content.indexOf(CUSTOM_START);
  while (start !== -1) {
    const end = content.indexOf(CUSTOM_END, start);
    if (end === -1) break;
    sections.push(content.slice(start, end + CUSTOM_END.length));
    start = content.indexOf(CUSTOM_START, end);
  }
  return sections.join("\n\n");
}

function buildProjectSections(project: string): string[] {
  const projectModel = readProjectModel(project);
  const m = projectModel.model;
  const results: string[] = [];

  if (m.techStack.length > 0) {
    const lines = ["## Tech Stack\n"];
    for (const t of m.techStack) lines.push("- " + t);
    lines.push("");
    results.push(lines.join("\n"));
  }

  if (m.conventions.length > 0) {
    const lines = ["## Conventions\n"];
    for (const c of m.conventions) lines.push("- " + c);
    lines.push("");
    results.push(lines.join("\n"));
  }

  if (m.procedures.length > 0) {
    const lines = ["## Procedures\n"];
    for (const p of m.procedures) lines.push("- " + p);
    lines.push("");
    results.push(lines.join("\n"));
  }

  if (m.activeWork.length > 0) {
    const lines = ["## Active Work\n"];
    for (const w of m.activeWork) lines.push("- " + w);
    lines.push("");
    results.push(lines.join("\n"));
  }

  if (m.openThreads.length > 0) {
    const lines = ["## Open Threads\n"];
    for (const t of m.openThreads) lines.push("- " + t);
    lines.push("");
    results.push(lines.join("\n"));
  }

  return results;
}

function buildGuardrailsSection(project: string): string {
  const antiPatterns = getAntiPatterns(project);
  if (antiPatterns.length === 0) return "";

  const lines: string[] = ["## Guardrails\n", "Do NOT:\n"];
  for (const ap of antiPatterns) {
    lines.push("- " + ap.gist);
  }
  lines.push("");
  return lines.join("\n");
}

function buildGlobalPreferencesSections(): string[] {
  const globalModel = readGlobalModel();
  const m = globalModel.model;
  const results: string[] = [];

  if (m.preferences.length > 0) {
    const lines = ["## User Preferences\n"];
    for (const p of m.preferences) lines.push("- " + p);
    lines.push("");
    results.push(lines.join("\n"));
  }

  if (m.decisionPatterns.length > 0) {
    const lines = ["## Decision Patterns\n"];
    for (const d of m.decisionPatterns) lines.push("- " + d);
    lines.push("");
    results.push(lines.join("\n"));
  }

  return results;
}

function buildGraphNodesSection(project: string): string {
  const projectNodes = getByProject(project);
  if (projectNodes.length === 0) return "";

  const lines: string[] = ["## Key Patterns & Decisions\n"];
  for (const node of projectNodes.slice(0, 15)) {
    lines.push("- **" + node.path + "**: " + node.gist);
  }
  lines.push("");
  return lines.join("\n");
}

export function bootstrapProjectDoc(
  project: string,
  harness: string,
  cwd: string
): BootstrapResult {
  const docPath = resolveDocPath(cwd, harness);
  const created = !fs.existsSync(docPath);

  let customContent = "";
  if (!created) {
    const existing = fs.readFileSync(docPath, "utf-8");
    customContent = extractCustomSections(existing);
  }

  const sections: string[] = [
    GRAPH_MEMORY_MARKER,
    "# Project Context — " + project,
    "",
    "_Auto-generated by graph-memory. Custom sections are preserved between regenerations._",
    "",
  ];

  const projectSections = buildProjectSections(project);
  for (const section of projectSections) {
    if (section) sections.push(section);
  }

  const guardrails = buildGuardrailsSection(project);
  if (guardrails) sections.push(guardrails);

  const globalPrefs = buildGlobalPreferencesSections();
  for (const section of globalPrefs) {
    if (section) sections.push(section);
  }

  const graphNodes = buildGraphNodesSection(project);
  if (graphNodes) sections.push(graphNodes);

  if (customContent) {
    sections.push(customContent);
    sections.push("");
  } else {
    sections.push(CUSTOM_START);
    sections.push("<!-- Add your custom instructions here. This section is preserved during re-bootstrap. -->");
    sections.push(CUSTOM_END);
    sections.push("");
  }

  const dir = path.dirname(docPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(docPath, sections.join("\n"));

  activityBus.log("system:info", "Project doc bootstrapped: " + docPath, {
    project,
    harness,
    created,
  });

  return {
    filePath: docPath,
    created,
    sections: sections.filter((s) => s.trimStart().startsWith("##")).map((s) => s.trim().split("\n")[0].replace("## ", "")),
  };
}

export function detectDocDrift(project: string, cwd: string, harness: string): { drifted: boolean; missing: string[] } {
  const docPath = resolveDocPath(cwd, harness);
  if (!fs.existsSync(docPath)) {
    return { drifted: true, missing: ["doc-missing"] };
  }

  const content = fs.readFileSync(docPath, "utf-8");
  if (!content.includes(GRAPH_MEMORY_MARKER)) {
    return { drifted: false, missing: [] };
  }

  const projectModel = readProjectModel(project);
  const m = projectModel.model;
  const missing: string[] = [];

  if (m.techStack.length > 0 && !content.includes("Tech Stack")) {
    missing.push("tech-stack");
  }
  if (m.conventions.length > 0 && !content.includes("Conventions")) {
    missing.push("conventions");
  }
  if (m.guardrails.length > 0 && !content.includes("Guardrails")) {
    missing.push("guardrails");
  }

  return { drifted: missing.length > 0, missing };
}
